[profile.default]
auto_detect_solc = false
ast = true
block_timestamp = 1_738_368_000  # Feb 1, 2025 at 00:00 GMT
block_gas_limit = 3000000000     # 3 billion gas limit
build_info = true
bytecode_hash = "none"
evm_version = "shanghai"
extra_output = ["storageLayout"]
fuzz = { runs = 1_000 }
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
via_ir = true
out = "out"
script = "script"
solc = "0.8.29"
src = "src"
test = "test"
ffi = true

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4
gas_reports = []
optimizer = true
optimizer_runs = 200
via_ir = false

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
